# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1614617578);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1614617698);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1614620822);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1614617458);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1614617338);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/home/embdtut/사진");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140715214327");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20140715214327");
user_pref("browser.startup.homepage_override.mstone", "31.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1613131388569");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1614614018184");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1614614047487");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1614700447487");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1600449198717");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1601215973190");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1599573518710");
user_pref("datareporting.sessions.current.activeTicks", 487);
user_pref("datareporting.sessions.current.firstPaint", 9207);
user_pref("datareporting.sessions.current.main", 747);
user_pref("datareporting.sessions.current.sessionRestored", 10271);
user_pref("datareporting.sessions.current.startTime", "1605163035418");
user_pref("datareporting.sessions.current.totalTime", 9459888);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 19);
user_pref("extensions.blocklist.pingCountVersion", 19);
user_pref("extensions.bootstrappedAddons", "{\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.9,%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2013.09.20.beta,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"online-accounts@lists.launchpad.net\":{\"descriptor\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"mtime\":1406067316000,\"rdfTime\":1390969548000}}},{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1406067315000,\"rdfTime\":1401829706000},\"webapps-team@lists.launchpad.net\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"mtime\":1406067316000,\"rdfTime\":1397665356000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"mtime\":1406067315000,\"rdfTime\":1379719396000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1554899883000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1554899883000},\"langpack-en-CA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-CA@firefox.mozilla.org.xpi\",\"mtime\":1554899883000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1406067038000,\"rdfTime\":1405462641000},\"langpack-ko@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ko@firefox.mozilla.org.xpi\",\"mtime\":1554899909000}}}]");
user_pref("extensions.lastAppVersion", "31.0");
user_pref("extensions.lastPlatformVersion", "31.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140715214327");
user_pref("gecko.mstone", "31.0");
user_pref("idle.lastDailyNotification", 1614623374);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1614614032);
user_pref("places.history.expiration.transient_current_max_pages", 52103);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("spellchecker.dictionary", "ko");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1613195613);
user_pref("toolkit.startup.last_success", 1605163036);
user_pref("toolkit.telemetry.previousBuildID", "20140715214327");
